---
- name: Create storage class configuration
  become: yes
  become_user: kube
  ansible.builtin.template:
    src: storage-class.j2
    dest: $HOME/storage-class.yaml
    mode: "0644"

- name: Apply storage class configuration
  become: yes
  become_user: kube
  command: kubectl apply -f $HOME/storage-class.yaml
