---
- name: Setup VM on bastion
  hosts: bastion
  gather_facts: yes
  become: yes
  roles:
    - { role: kubernetes/setup-vm, tags: 'setup-vm' }

- name: Setup VM on cluster nodes
  hosts: k8s_master, k8s_worker
  gather_facts: yes
  become: yes
  roles:
    - { role: kubernetes/setup-vm, tags: 'setup-vm' }

- name: Setup volumes on cluster nodes
  hosts: k8s_master, k8s_worker
  gather_facts: yes
  become: yes
  roles:
    - { role: kubernetes/setup-volumes, tags: 'setup-volumes' }

- name: Setup firewall on cluster nodes
  hosts: k8s_master, k8s_worker
  gather_facts: yes
  become: yes
  roles:
    - { role: kubernetes/setup-firewall, tags: 'setup-firewall' }

- name: Setup containerd on cluster nodes
  hosts: k8s_master, k8s_worker
  gather_facts: yes
  become: yes
  roles:
    - { role: kubernetes/setup-containerd, tags: 'setup-containerd' }

- name: Install Kubernetes on cluster nodes
  hosts: k8s_master, k8s_worker
  gather_facts: yes
  become: yes
  roles:
    - { role: kubernetes/install-kubernetes, tags: 'install-kubernetes' }

- name: Setup Kubernetes node on cluster nodes
  hosts: k8s_master, k8s_worker
  gather_facts: yes
  become: yes
  roles:
    - { role: kubernetes/setup-kubernetes-node, tags: 'setup-kubernetes-node' }

- name: Setup master node
  hosts: k8s_master
  gather_facts: yes
  become: yes
  roles:
    - { role: kubernetes/setup-master-node, tags: 'setup-master-node' }

- name: Setup worker node
  hosts: k8s_worker
  gather_facts: yes
  become: yes
  roles:
    - { role: kubernetes/setup-worker-node, tags: 'setup-worker-node' }
