---
- name: Load AWS credentials from ~/.aws/credentials file
  ansible.builtin.set_fact:
    kubernetes_aws_access_key_id: "{{ lookup('ini', 'aws_access_key_id section={{ aws_profile }} file=~/.aws/credentials') }}"
    kubernetes_aws_secret_access_key: "{{ lookup('ini', 'aws_secret_access_key section={{ aws_profile }} file=~/.aws/credentials') }}"
  vars:
    profile: "{{ aws_profile }}"

- name: List Linux block devices
  ansible.builtin.shell:
    cmd: "set -o pipefail && lsblk -o PATH,SIZE,SERIAL | grep ' vol' | sed 's/ vol/ vol-/'"
    executable: /bin/bash
  register: kubernetes_lsblk
  changed_when: false

- name: Store EBS volume device name
  ansible.builtin.set_fact:
    kubernetes_ebs_volume_device_name: "{{ kubernetes_lsblk.stdout_lines }}"

- name: Local Instance Device Names
  ansible.builtin.debug:
    msg: "Device name: {{ kubernetes_ebs_volume_device_name }}"

# The url is from the below documentation and it is specific to the instance
# https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instancedata-data-retrieval.html
# https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-instance-addressing.html#link-local-addresses
- name: Get hostname
  ansible.builtin.uri:
    url: "http://169.254.169.254/latest/meta-data/instance-id"
    return_content: yes
  register: kubernetes_instance_id

- name: Store hostname
  ansible.builtin.set_fact:
    kubernetes_instance_id: "{{ kubernetes_instance_id.content }}"

- name: debug output
  ansible.builtin.debug:
    msg: "Device name: {{ instance_volumes.keys() | join(',') }}"

- name: Fetch EC2 volume facts
  amazon.aws.ec2_vol_info:
    aws_access_key: "{{ kubernetes_aws_access_key_id }}"
    aws_secret_key: "{{ kubernetes_aws_secret_access_key }}"
    region: "{{ region }}"
    filters:
      attachment.instance-id: "{{ kubernetes_instance_id }}"
      tag:Name: "{{ instance_volumes.keys() }}"
  register: kubernetes_ec2_volumes

- name: Display volume IDs and tags
  debug:
    msg: "Volume device: {{ item }}"
  loop: "{{ kubernetes_ec2_volumes.volumes }}"

- name: Split ebs_volume_device_name variable
  set_fact:
    kubernetes_split_ebs_volume_device_name: "{{ kubernetes_ebs_volume_device_name | map('regex_replace', '\\s+', ' ') | map('split', ' ') | list }}"

- name: Display split ebs_volume_device_name
  debug:
    msg: "{{ kubernetes_split_ebs_volume_device_name }}"

- name: Initialize volume info dictionary
  set_fact:
    kubernetes_volume_info: {}

- name: Extract volume IDs from ebs_volume_device_name
  set_fact:
    kubernetes_ebs_volume_ids: []

- name: Loop over each EC2 volume
  ansible.builtin.set_fact:
    kubernetes_volume_info: "{{ kubernetes_volume_info | combine({item.id: {'tag': tag, 'size': size, 'device': device, 'volume_name': volume_name}}) }}"
  loop: "{{ kubernetes_ec2_volumes.volumes }}"
  vars:
    device: "{{ item.attachment_set[0].device }}"
    tag: "{{ item.tags.Name | default('Unknown') }}"
    size: "{{ item.size }}G"
    volume_name: "{{ kubernetes_split_ebs_volume_device_name | selectattr('2', 'search', item.id) | map('first') | first }}"
  when: item.id in kubernetes_split_ebs_volume_device_name | map(attribute=2)

- name: Display volume information
  debug:
    msg: "{{ kubernetes_volume_info }}"

- name: Create disk partitions
  community.general.parted:
    device: "{{ item.value.volume_name }}"
    number: 1
    flags: [lvm]
    state: present
  loop: "{{ kubernetes_volume_info | dict2items }}"

- name: Format disk partition
  community.general.filesystem:
    fstype: xfs
    dev: "{{ item.value.volume_name }}p1"
  loop: "{{ kubernetes_volume_info | dict2items }}"

- name: Create mount point directories
  file:
    path: "/{{ item.value.tag }}"
    state: directory
    mode: "0775"
  loop: "{{ kubernetes_volume_info | dict2items }}"

- name: Get UUID for volume
  ansible.builtin.command:
    cmd: "blkid -s UUID -o value {{ item.value.volume_name }}p1"
  register: kubernetes_uuid
  loop: "{{ kubernetes_volume_info | dict2items }}"
  vars:
    mount_point: "/{{ item.value.tag }}"
  changed_when: false

- name: Store UUID values
  ansible.builtin.set_fact:
    kubernetes_uuid_device: "{{ kubernetes_uuid_device | default({}) | combine({item.item.value.tag: item.stdout_lines[0]}) }}"
  loop: "{{ kubernetes_uuid.results }}"

- name: Debug UUIDs
  ansible.builtin.debug:
    var: kubernetes_uuid_device

- name: Mount volumes
  ansible.posix.mount:
    path: "/{{ item.value.tag }}"
    src: "UUID={{ kubernetes_uuid_device[item.value.tag] }}"
    fstype: xfs
    state: mounted
  loop: "{{ kubernetes_volume_info | dict2items }}"
  vars:
    kubernetes_uuid_device: "{{ kubernetes_uuid_device }}"
