---
- name: Run apt update before installing prerequisites
  apt:
    update_cache: yes

- name: 2.1.start_firewalld
  ansible.builtin.systemd:
    name: firewalld
    state: started

- name: 2.2.enable_firewalld
  ansible.builtin.systemd:
    name: firewalld
    enabled: yes

- name: 2.3.status_firewalld
  command: systemctl status firewalld.service
  changed_when: false

- name: 2.4.add_firewall_rules_public
  command: firewall-cmd --permanent --zone=public --add-port={{ item }}
  loop: "{{ ports_to_open }}"
  changed_when: "'success' in kubernetes_firewall_public.stdout or kubernetes_firewall_public.rc == 0"
  register: kubernetes_firewall_public

- name: 2.4.add_firewall_rules_trusted
  command: firewall-cmd --permanent --zone=trusted --add-port={{ item }}
  loop: "{{ ports_to_open }}"
  changed_when: "'success' in kubernetes_firewall_trusted.stdout or kubernetes_firewall_trusted.rc == 0"
  register: kubernetes_firewall_trusted

- name: add service cidr in trusted zone
  command: firewall-cmd --permanent --zone=trusted --add-source={{ service_cidr }}
  changed_when: "'success' in kubernetes_firewall_service_cidr.stdout or kubernetes_firewall_service_cidr.rc == 0"
  register: kubernetes_firewall_service_cidr

- name: add pod cidr in trusted zone
  command: firewall-cmd --permanent --zone=trusted --add-source={{ pod_network_cidr }}
  changed_when: "'success' in kubernetes_firewall_pod_cidr.stdout or kubernetes_firewall_pod_cidr.rc == 0"
  register: kubernetes_firewall_pod_cidr

- name: Get list of master nodes
  set_fact:
    kubernetes_master_ips: "{{ groups['k8s_master'] | list }}"
    kubernetes_worker_ips: []

- name: Get list of worker nodes
  set_fact:
    kubernetes_worker_ips: "{{ groups['k8s_worker'] | list }}"
  when:
    - "'k8s-worker' in groups"

- name: add master hosts in trusted zone
  command: firewall-cmd --permanent --zone=trusted --add-source={{ item }}
  loop: "{{ kubernetes_master_ips }}"
  changed_when: "'success' in kubernetes_firewall_master_hosts.stdout or kubernetes_firewall_master_hosts.rc == 0"
  register: kubernetes_firewall_master_hosts

- name: add worker hosts in trusted zone
  command: firewall-cmd --permanent --zone=trusted --add-source={{ item }}
  loop: "{{ kubernetes_worker_ips }}"
  changed_when: "'success' in kubernetes_firewall_worker_hosts.stdout or kubernetes_firewall_worker_hosts.rc == 0"
  register: kubernetes_firewall_worker_hosts

- name: 2.6.reload_firewall
  command: firewall-cmd --reload
  changed_when: false
